export const dwGMdata = {
  gmMoves: [
    "Introduce a monster",
    "Introduce a danger from your fronts",
    "Introduce an environmental threat or hazard",
    "Reveal an unwelcome truth",
    "Show signs of an approaching threat",
    "Deal damage",
    "Use up their resources",
    "Turn their move back on them",
    "Separate them",
    "Give an opportunity that fits a class's abilities",
    "Show a downside to their class, race, or equipment",
    "Offer an opportunity, with or without cost",
    "Put someone in a spot",
    "Tell them the requirements or consequences then ask",
    "Make them wish they didn't succeed"
  ],
  npcName: [
    "Alvira",
  	"Antionette",
  	"Apalie",
  	"Ardis",
  	"Arlyne",
  	"Arta",
  	"Amaka",
  	"Bernadine",
  	"Berta",
  	"Brinda",
  	"Brittany",
  	"Caldonia",
  	"Carisa",
  	"Coleen",
  	"Caelie",
  	"Danita",
  	"Durga",
  	"Dayle",
  	"Deanne",
  	"Elmira",
  	"Evgenia",
  	"Euphemia",
  	"Evon",
  	"Fadia",
  	"Frederica",
  	"Francisca",
  	"Geri",
  	"Galadriel",
  	"Gildas",
  	"Hadya",
  	"Hettie",
  	"Iria",
  	"Judie",
  	"Jumana",
  	"Krystal",
  	"Lakendra",
  	"Lashonda",
  	"Latisha",
  	"Lovisa",
  	"Lucretia",
  	"Mara",
  	"Mercia",
  	"Manda",
  	"Marilou",
  	"Misty",
  	"Myrtle",
  	"Neola",
  	"Norine",
  	"Orah",
  	"Padma",
  	"Quianna",
  	"Renita",
  	"Rozella",
  	"Sabela",
  	"Shanika",
  	"Sharee",
  	"Shavon",
  	"Tacy",
  	"Tari",
  	"Teela",
  	"Trish",
  	"Uliana",
  	"Viveka",
  	"Velia",
  	"Zela",
  	"Zoa",
  	"Zenaida",
  	"Algernon",
  	"Allison",
  	"Alvan",
  	"Anna",
  	"Arc",
  	"Attilio",
  	"Balda",
  	"Bart",
  	"Berlin",
  	"Bliss",
  	"Boucama",
  	"Buford",
  	"Burley",
  	"Burnell",
  	"Butch",
  	"Ceaser",
  	"Chauncy",
  	"Cheyenne",
  	"Christopher",
  	"Clair",
  	"Clara",
  	"Darryll",
  	"Dee",
  	"Delmer",
  	"Delwin",
  	"Dewitt",
  	"Dock",
  	"Dominque",
  	"Donal",
  	"Dorsey",
  	"Durell",
  	"Dwain",
  	"Egbert",
  	"Einar",
  	"Elayne",
  	"Ella",
  	"Erling",
  	"Eva",
  	"Ezell",
  	"Frances",
  	"Garvin",
  	"Glynn",
  	"Hall",
  	"Handy",
  	"Harden",
  	"Hartford",
  	"Hill",
  	"Hoke",
  	"James",
  	"Jas",
  	"Jefferey",
  	"Jerad",
  	"Jessica",
  	"Joyce",
  	"Justine",
  	"Justo",
  	"Kay",
  	"Kiley",
  	"Kiyoshi",
  	"Kristin",
  	"Lafe",
  	"Leigh",
  	"Lennie",
  	"Lin",
  	"Lonzo",
  	"Love",
  	"Loyd",
  	"Mannie",
  	"Mervyn",
  	"Milas",
  	"Norbert",
  	"Ora",
  	"Orie",
  	"Orland",
  	"Orlo",
  	"Orren",
  	"Ozell",
  	"Quince",
  	"Rae",
  	"Randel",
  	"Redden",
  	"Rob",
  	"Roby",
  	"Roney",
  	"Rose",
  	"Samantha",
  	"Sitid",
  	"Shivara",
  	"Shyheim",
  	"Theodis",
  	"Waldemar",
  	"Waverly",
  	"Winthrop",
  	"Young",
  	"Abu",
  	"Agapito",
  	"Akachi",
  	"Alborz",
  	"Aldrais",
  	"Alexius",
  	"Amedeo",
  	"Amery",
  	"Amichai",
  	"Anan",
  	"Ananth",
  	"Andras",
  	"Andria",
  	"Antero",
  	"Antonello",
  	"Aragorn",
  	"Aubin",
  	"Barclay",
  	"Basile",
  	"Basit",
  	"Berk",
  	"Bernardino",
  	"Brand",
  	"Breno",
  	"Burak",
  	"Celio",
  	"Chen",
  	"Chidiebube",
  	"Chike",
  	"Cosmas",
  	"Damyan",
  	"Darragh",
  	"Deniel",
  	"Devereux",
  	"Dionysus",
  	"Drago",
  	"Eberardo",
  	"Eelis",
  	"Eldad",
  	"Emanuele",
  	"Emigdio",
  	"Endre",
  	"Enric",
  	"Enver",
  	"Finbar",
  	"Fortunato",
  	"Franck",
  	"Fraser",
  	"Georgiy",
  	"Gianpaolo",
  	"Gilead",
  	"Goliath",
  	"Gordy",
  	"Guillaume",
  	"Haeron",
  	"Haig",
  	"Halil",
  	"Hameed",
  	"Hasim",
  	"Hatim",
  	"Hikaru",
  	"Hyun",
  	"Ikram",
  	"Irathan",
  	"Isidoro",
  	"Les",
  	"Roshan",
  	"Sammael",
  	"Toben",
  	"Zephyr",
  	"Isoru"
  ],
  npcQuirk: [
  	"believes all religions are cults",
  	"believes in aliens",
  	"believes in demonic possession",
  	"believes in karma",
  	"believes the moon gives him special powers",
  	"believes the world will end soon",
  	"carries a 'lucky' item with them everywhere",
  	"hates conflict",
  	"is always trying to recruit people to their religion/philosophical beliefs",
  	"is extremely superstitious",
  	"meditates",
  	"practices voodoo",
  	"refuses to hurt any animal, including insects",
  	"only wears a certain color",
  	"refuses to wear shoes",
  	"wears lots of bracelets",
  	"counts money in pockets once a day",
  	"counts own teeth",
  	"counts stairs",
  	"counts stars",
  	"counts steps taken while walking",
  	"has insomnia",
  	"has narcolepsy",
  	"hears voices",
  	"is a pathological liar",
  	"collects insects",
  	"doodles on everything",
  	"hates the outdoors",
  	"hunts animals",
  	"is always reading",
  	"juggles",
  	"keeps up with the weather obsessively",
  	"loves playing practical jokes",
  	"loves to hide and scare people",
  	"randomly wanders around/gets lost when bored",
  	"has a miscellaneous phobia",
  	"is afraid of or hates a certain color",
  	"is afraid of animals",
  	"is afraid of dogs",
  	"is afraid of cats",
  	"is afraid of insects",
  	"is afraid of snakes",
  	"is agoraphobic",
  	"is claustrophobic",
  	"is constantly paranoid",
  	"always has to be snacking on something",
  	"is vegetarian, because 'murder'",
  	"drinks alcohol excessively",
  	"doesn’t brush teeth",
  	"habitually coughs/clears throat ",
  	"habitually sniffles",
  	"has a large visible scar",
  	"has allergies",
  	"is gassy",
  	"is hearing-impaired",
  	"is vision-impaired",
  	"sneezes loudly",
  	"sneezes many times in a row",
  	"sweats profusely",
  	"wears glasses",
  	"wears headgear",
  	"works out excessively",
  	"has many pets",
  	"always feels dirty",
  	"always stands with hands behind their back",
  	"always shreds random pieces of paper",
  	"avoids eye contact",
  	"blinks repeatedly",
  	"bites lip",
  	"bites nails",
  	"cannot keep still",
  	"constantly adjusts clothing",
  	"constantly adjusts glasses",
  	"constantly bumps into or knocks over things",
  	"constantly squints",
  	"cracks neck/back",
  	"cracks knuckles",
  	"fidgets constantly",
  	"has a beard",
  	"has a moustache",
  	"has a noticeable birthmark",
  	"has an eye twitch",
  	"has body piercings",
  	"has brightly colored hair",
  	"has extremely hairy arms",
  	"has facial piercings",
  	"has tattoos",
  	"hates being touched",
  	"is always touching their face",
  	"is bald",
  	"is extremely clumsy",
  	"is extremely ticklish",
  	"is late to everything",
  	"loves to hug",
  	"picks nose",
  	"picks skin",
  	"plays with hair",
  	"pulls on earrings",
  	"regularly looks up at the sky, sun, or moon",
  	"taps foot when bored or nervous",
  	"tends to drag feet",
  	"walks with a limp",
  	"whistles",
  	"winks without realizing",
  	"sleeps during the day",
  	"sleep-talks",
  	"sleep-walks",
  	"always answers a question with a question",
  	"always gives the vaguest possible answer to questions",
  	"always laughs at own jokes",
  	"always lets out a nervous laugh before speaking",
  	"curses constantly",
  	"flirts with everyone",
  	"goes off on tangents",
  	"gossips constantly",
  	"has a catchphrase they use whenever possible",
  	"has a lisp",
  	"has a stutter",
  	"has an unusually high-pitched voice",
  	"has an unusually low-pitched voice",
  	"has to touch whoever they are speaking to",
  	"interrupts",
  	"is extremely sarcastic",
  	"laughs at everything",
  	"laughs to self randomly or for no reason",
  	"mutters things under their breath",
  	"pauses a lot while speaking",
  	"plays dumb",
  	"puts others down constantly",
  	"says 'like' a lot",
  	"says 'right?' a lot",
  	"says 'um' or 'uh' a lot",
  	"says 'you know' a lot",
  	"sees a dirty/sexual reference in everything",
  	"spaces out and stares when someone is talking for a while",
  	"speaks in third person",
  	"talks to animals",
  	"talks to inanimate objects",
  	"talks to self",
  	"talks very loudly",
  	"talks very quietly",
  	"tells 'stories' with no point or conclusion",
  	"tells the truth/is brutally honest no matter what",
  	"uses big words to impress others",
  	"uses lots of metaphors",
  	"uses pet names for everyone",
  	"uses poor grammar",
  	"uses slang whenever possible",
  	"yawns a lot"
  ],
  npcInstinct: [
  	"To avenge",
  	"To spread the good word",
  	"To reunite with a loved one",
  	"To make money",
  	"To make amends",
  	"To explore a mysterious place",
  	"To uncover a hidden truth",
  	"To locate a lost thing",
  	"To kill a hated foe",
  	"To conquer a faraway land",
  	"To cure an illness",
  	"To craft a masterwork",
  	"To survive just one more day",
  	"To earn affection",
  	"To prove a point",
  	"To be smarter, faster and stronger",
  	"To heal an old wound",
  	"To extinguish an evil forever",
  	"To hide from a shameful fact",
  	"To evangelize",
  	"To spread suffering",
  	"To prove worth",
  	"To rise in rank",
  	"To be praised",
  	"To discover the truth",
  	"To make good on a bet",
  	"To get out of an obligation",
  	"To convince someone to do their dirty work",
  	"To steal something valuable",
  	"To overcome a bad habit",
  	"To commit an atrocity",
  	"To earn renown",
  	"To accumulate power",
  	"To save someone from a monstrosity",
  	"To teach",
  	"To settle down",
  	"To get just one more haul",
  	"To preserve the law",
  	"To discover",
  	"To devour",
  	"To restore the family name",
  	"To live the quiet life",
  	"To help others",
  	"To atone",
  	"To prove their worth",
  	"To gain honor",
  	"To expand their land",
  	"To gain a title",
  	"To retreat from society",
  	"To escape",
  	"To party",
  	"To return home",
  	"To serve",
  	"To reclaim what was taken",
  	"To do what must be done",
  	"To be a champion",
  	"To avoid notice",
  	"To help a family member",
  	"To perfect a skill",
  	"To travel",
  	"To overcome a disadvantage",
  	"To play the game",
  	"To establish a dynasty",
  	"To improve the realm",
  	"To retire",
  	"To recover a lost memory",
  	"To battle",
  	"To become a terror to criminals",
  	"To raise dragons",
  	"To live up to expectations",
  	"To become someone else",
  	"To do what can't be done",
  	"To be remembered in song",
  	"To be forgotten",
  	"To find true love",
  	"To lose their mind",
  	"To indulge",
  	"To make the best of it",
  	"To find the one",
  	"To destroy an artifact",
  	"To show them all",
  	"To bring about unending summer",
  	"To fly",
  	"To find the six-fingered man",
  	"To wake the ancient sleepers",
  	"To entertain",
  	"To follow an order",
  	"To die gloriously",
  	"To be careful",
  	"To show kindness",
  	"To not screw it all up",
  	"To uncover the past",
  	"To go where no man has gone before",
  	"To do good",
  	"To become a beast",
  	"To spill blood",
  	"To live forever",
  	"To hunt the most dangerous game",
  	"To hate",
  	"To run away"
  ],
  npcKnack: [
  	"Criminal connections",
  	"Muscle",
  	"Skill with a specific weapon",
  	"Hedge wizardry",
  	"Comprehensive local knowledge",
  	"Noble blood",
  	"A one-of-a-kind item",
  	"Special destiny",
  	"Unique perspective",
  	"Hidden knowledge",
  	"Magical awareness",
  	"Abnormal parentage",
  	"Political leverage",
  	"A tie to a monster",
  	"A secret",
  	"True love",
  	"An innocent heart",
  	"A plan for the perfect crime",
  	"A one-way ticket to paradise",
  	"A mysterious ore",
  	"Money, money, money",
  	"Divine blessing",
  	"immunity from the law",
  	"Prophecy",
  	"Secret martial arts techniques",
  	"A ring of power",
  	"A much-needed bag of taters",
  	"A heart",
  	"A fortified position",
  	"Lawmaking",
  	"Tongues",
  	"A discerning eye",
  	"Endurance",
  	"A safe place",
  	"Visions",
  	"A beautiful mind",
  	"A clear voice",
  	"Stunning looks",
  	"A catchy tune",
  	"Invention",
  	"Baking",
  	"Brewing",
  	"Smelting",
  	"Woodworking",
  	"Writing",
  	"Immunity to fire",
  	"Cooking",
  	"Storytelling",
  	"Rat-catching",
  	"Lying",
  	"Utterly unremarkable",
  	"Mind-bending sexiness",
  	"Undefinable coolness",
  	"A way with knots",
  	"Wheels of polished steel",
  	"A magic carpet",
  	"Endless ideas",
  	"Persistence",
  	"A stockpile of food",
  	"A hidden path",
  	"Piety",
  	"Resistance to disease",
  	"A library",
  	"A silver tongue",
  	"Bloodline",
  	"An innate spell",
  	"Balance",
  	"Souls",
  	"Speed",
  	"A sense of right and wrong",
  	"Certainty",
  	"An eye for detail",
  	"Heroic self-sacrifice",
  	"Sense of direction",
  	"A big idea",
  	"A hidden entrance to the city",
  	"The love of someone powerful",
  	"Unquestioning loyalty",
  	"Exotic fruit",
  	"Poison",
  	"Perfect memory",
  	"The language of birds",
  	"A key to an important door",
  	"Metalworking",
  	"Mysterious benefactors",
  	"Steely nerves",
  	"Bluffing",
  	"A trained wolf",
  	"A long-lost sibling, regained",
  	"An arrow with your name on it",
  	"A true name",
  	"Luck",
  	"The attention of supernatural powers",
  	"Kindness",
  	"Strange tattoos",
  	"A majestic beard",
  	"A book in a strange language",
  	"Power overwhelming",
  	"Delusions of grandeur",
  	"The wind at their back and a spring in their step"
  ],
  magicItemAdj: [
  	"accepting",
  	"all-knowing",
    "all-seeing",
    "angelic",
  	"awful",
  	"bashful",
    "befuddling",
  	"binding",
    "black",
    "blazing",
    "blinding",
    "bloody",
    "bright",
  	"cacophonous",
  	"ceaseless",
  	"confusing",
  	"concealing",
  	"consuming",
    "crimson",
  	"cuddly",
  	"cute",
  	"damnable",
  	"dark",
    "deflecting",
    "delicate",
    "demonic",
    "devastating",
    "devilish",
  	"diligent",
    "diminishing",
  	"disastrous",
  	"disgusting",
  	"draining",
  	"eldritch",
    "empowering",
    "enlightening",
    "ensorcelling",
    "entangling",
    "enveloping",
    "erratic",
    "evil",
    "excruciating",
    "expanding",
    "fearsome",
    "flaming",
    "flashing",
    "floating",
    "freezing",
  	"fumbling",
  	"glittering",
  	"glossy",
  	"graceful",
    "gyrating",
  	"hard",
  	"helpful",
  	"hindering",
  	"icy",
  	"incandescent",
    "incredible",
    "inescapable",
    "ingenious",
  	"inquisitive",
  	"insane",
    "instant",
  	"intelligent",
  	"irritating",
    "invigorating",
    "invisible",
    "invulnerable",
  	"lavish",
  	"lewd",
  	"liberating",
    "maddening",
    "magnificent",
  	"maniacal",
    "many-colored",
    "mighty",
  	"miniature",
  	"minor",
  	"misty",
  	"moaning",
  	"momentous",
  	"nifty",
  	"omnipotent",
    "oozing",
  	"painful",
  	"penitent",
  	"perpetual",
    "piercing",
    "poisonous",
  	"powerful",
    "prismatic",
    "raging",
    "rejuvenating",
  	"remarkable",
    "restorative",
  	"robust",
  	"scandalous",
    "screaming",
    "sensitive",
    "shimmering",
    "shining",
  	"shocking",
  	"silent",
  	"silly",
  	"sleeping",
    "slow",
    "smoking",
    "sorcerer's",
  	"spotted",
  	"squealing",
  	"strange",
  	"stupefying",
  	"sweltering",
    "terrible",
    "thirsty",
    "thundering",
    "trans-dimensional",
  	"ultimate",
    "uncontrollable",
    "unseen",
    "unstoppable",
  	"unsuitable",
    "vengeful",
    "vexing",
    "violent",
    "violet",
    "voracious",
  	"vulgar",
    "weakening",
    "white",
  	"wicked",
    "wonderous",
  	"zealous"
  ],
  magicItemNoun: [
    "armor",
    "arrow",
    "aura",
    "axe",
    "badge",
    "bag",
    "bane",
    "ball",
    "bells",
    "blade",
    "blob",
    "blood",
    "blunderbuss",
    "bolt",
    "bomb",
    "book",
    "boots",
    "bottle",
    "bow",
    "bracelet",
    "brain",
    "cannon",
    "charm",
    "cheese",
    "claw",
    "cloak",
    "coin",
    "collar",
    "corset",
    "crown",
    "cube",
    "cup",
    "dagger",
    "dart",
    "demon",
    "dog",
    "drum",
    "earrings",
    "eye",
    "eyes",
    "face",
    "fang",
    "fangs",
    "finger",
    "fists",
    "flute",
    "gauntlet",
    "globe",
    "gloves",
    "hammer",
    "hand",
    "hat",
    "heart",
    "helm",
    "hood",
    "horn",
    "horse",
    "ink",
    "jar",
    "mace",
    "marble",
    "monkey",
    "morning star",
    "mouth",
    "necklace",
    "orb",
    "pauldrons",
    "pet",
    "pig",
    "portal",
    "pyramid",
    "ring",
    "rock",
    "rod",
    "rope",
    "rose",
    "rune",
    "sack",
    "sand",
    "sandals",
    "scarf",
    "scissors",
    "scroll",
    "shield",
    "shinguards",
    "shoes",
    "sigil",
    "snail",
    "song",
    "songbook",
    "spear",
    "sphere",
    "staff",
    "stocking",
    "stone",
    "sword",
    "tendril",
    "tiger",
    "toad",
    "tongue",
    "tooth",
    "trap",
    "vial",
    "veil",
    "wand",
    "whistle",
    "wings",
    "wine"
  ],
  magicItemElement: [
      "acid",
    	"air",
    	"alert",
    	"amusement",
      "anger",
    	"arguement",
      "ash",
    	"attraction",
      "balance",
      "blight",
    	"blindness",
      "bone",
    	"breath",
      "brimstone",
    	"bruises",
    	"chewing",
    	"choking",
      "clay",
      "cloud",
    	"confession",
    	"conjuration",
      "copper",
      "cosmos",
      "dark",
      "death",
    	"decay",
    	"deceit",
      "despair",
    	"destruction",
      "dimension",
    	"disappearance",
    	"disarmament",
    	"discovery",
      "doom",
      "dust",
    	"earth",
    	"elementalism",
      "ember",
      "energy",
    	"entertainment",
      "envy",
    	"explosion",
    	"fade",
    	"failure",
    	"fear",
    	"fire",
      "fog",
      "force",
      "fury",
      "glory",
    	"glow",
      "gluttony",
      "gold",
      "greed",
    	"growth",
      "hate",
      "hatred",
      "health",
      "heat",
      "history",
      "hope",
    	"ice",
    	"illumination",
    	"illusion",
    	"influence",
    	"injury",
      "iron",
    	"itch",
    	"judgement",
    	"knowledge",
    	"laughter",
      "lead",
      "lies",
      "life",
    	"light",
      "lightning",
      "lore",
      "love",
      "lust",
      "metal",
      "might",
      "mist",
      "moon",
      "mud",
      "nature",
    	"necromancy",
    	"oil",
      "pain",
    	"perception",
      "poison",
    	"punishment",
      "quicksilver",
    	"repair",
      "revulsion",
    	"rhyme",
      "rot",
      "salt",
      "scent",
    	"shadow",
    	"sight",
    	"smoke",
    	"soil",
    	"souls",
    	"spirit",
    	"stars",
      "steam",
      "steel",
      "stone",
      "sun",
    	"surprise",
    	"temptation",
      "terror",
    	"thunder",
      "time",
      "treasure",
      "truth",
      "vanity",
      "vigor",
      "water",
      "wind",
      "wisdom",
      "wood",
      "youth"
    ]
}

export default dwGMdata;
