export const riverNameDictionary = [
  "Amielia",
  "Belis",
  "Nassau",
  "South",
  "Thomas",
  "Fort George",
  "Saint Mary",
  "Saint John",
  "Sisters",
  "Broward",
  "Trout",
  "Ribault",
  "Little Trout",
  "Arlington",
  "Pottsburg",
  "Ortega",
  "Cedar",
  "Julington",
  "Black",
  "Rice",
  "Dunns",
  "Ocklawaha",
  "Orange",
  "Styx",
  "Cross",
  "Silver",
  "Haines",
  "Dead",
  "Palatlakaha",
  "Salt Springs",
  "Alexander Springs",
  "Hontoon",
  "Wekiva",
  "Blackwater",
  "Econlockhatchee",
  "Tolomato",
  "San Sebastian",
  "Halifax",
  "Spruce",
  "Tomoka",
  "Banana",
  "Elbow",
  "Crane",
  "Turkey",
  "Saint Lucie",
  "Loxahatchee",
  "Hillsboro",
  "Stranahan",
  "New",
  "Middle",
  "Oleta",
  "Miami",
  "Bivens",
  "Tumbling",
  "Sweetwater",
  "Prairie",
  "Newnan",
  "Hatchet",
  "Forest",
  "Chacala",
  "Sawgrass",
  "Wauburg",
  "Burnt",
  "Dog",
  "Fisheating",
  "Kissimmee",
  "Reedy",
  "Bonnet",
  "Cypress",
  "Taylor",
  "Joe",
  "Shark",
  "Harney",
  "Broad",
  "Rodgers",
  "Lostman",
  "Chatham",
  "Huston",
  "Lopez",
  "Turner",
  "Barron",
  "Fakahatchee",
  "Whitney",
  "Caloosahatchee",
  "Estero",
  "Peace",
  "Myakka",
  "Manatee",
  "Anclote",
  "Weeki Watchee",
  "Homosassa",
  "Withlacoochee",
  "Waccasassa",
  "Suwannee",
  "Ichetucknee",
  "Alapatha",
  "Steinhatchee",
  "Fenholloway",
  "Econtina",
  "Aucilla",
  "Ochlockonee",
  "Crooked",
  "Carrabelle",
  "Econtina",
  "Chattahoochee",
  "East Bay",
  "Yellow",
  "Escambia",
  "Perdido",
  "Alabaha",
  "Alan",
  "Alapaha",
  "Alapahoochee",
  "Alcovy",
  "Alley",
  "Allez",
  "Alligator",
  "Altamaha",
  "Apalachee",
  "Aucilla",
  "Bear",
  "Beech",
  "Belfast",
  "Big Satilla",
  "Big Satilla",
  "Black",
  "Black",
  "Black",
  "Brier",
  "Broad",
  "Broro",
  "Brunswick",
  "Buffalo",
  "Bull",
  "Bull",
  "Camp",
  "Caney",
  "Canoochee",
  "Cartecay",
  "Chattahoochee",
  "Chattooga",
  "Chattooga",
  "Chestatee",
  "Coleman",
  "Coleoatchee",
  "Conasauga",
  "Coosa",
  "Coosawattee",
  "Crescent",
  "Crooked",
  "Crooked",
  "Cumberland",
  "Darien",
  "Deep",
  "Dog",
  "Duplin",
  "Ebenezer",
  "Ellijay",
  "Etowah",
  "Flat Shoal",
  "Flint",
  "Foe Killer",
  "Frederica",
  "Gum Swamp",
  "Halfmoon",
  "Hampton",
  "Hannahatchee",
  "Hazel",
  "Herb",
  "Hiwassee",
  "Hog Wallow",
  "Hudson",
  "Ichawaynochaway",
  "Jacks",
  "Jerico",
  "Johns",
  "Johns",
  "Kettle",
  "Kinchafoonee",
  "Knoxboro",
  "Laurel View",
  "Law",
  "Liberty",
  "Lick Log",
  "Little Hazel",
  "Little Ochlockonee",
  "Little Ocmulgee",
  "Little Ogeechee",
  "Little Ogeechee",
  "Little Ohoopee",
  "Little Satilla",
  "Little Satilla",
  "Little Tallapoosa",
  "Little Tennessee",
  "Mackay",
  "Medway",
  "Middle Oconee",
  "Mountain Oak",
  "Muckalee",
  "Mud",
  "Mulberry",
  "Mulberry",
  "Nancy",
  "New",
  "New",
  "Noonday",
  "North Newport",
  "North Oconee",
  "North",
  "North",
  "Noses",
  "Nottely",
  "Ochlockonee",
  "Ocmulgee",
  "Oconee",
  "Odingsell",
  "Ogeechee",
  "Ohoopee",
  "Okapilco",
  "Oostanaula",
  "Pataula",
  "Peachtree",
  "Styx",
  "Rocky Comfort",
  "Runaway Negro",
  "Saint Mary",
  "Sapelo",
  "Satilla",
  "Savannah",
  "Sawhatchee",
  "Sewell Mill",
  "Shad",
  "Shoal",
  "Sixteen Mile",
  "Skidaway",
  "Sope",
  "Soquee",
  "South Newport",
  "South",
  "Spring",
  "Suwannee",
  "Suwannoochee",
  "Sweetwater",
  "Swift",
  "Tallapoosa",
  "Tallulah",
  "Tesnatee",
  "Tivoli",
  "Tobesofkee",
  "Toccoa",
  "Towaliga",
  "Tugaloo",
  "Turtle",
  "Upatoi",
  "Vernon",
  "Vickery",
  "Willacoochee",
  "Willeo",
  "Williamson",
  "Wilmington",
  "Withlacoochee",
  "Yellow",
  "Yellowjacket",
  "Ashepoo",
  "Ashley",
  "Back",
  "Bates Old",
  "Beaufort",
  "Black",
  "Black Mingo",
  "Broad",
  "Broad",
  "Bull Swamp",
  "Bush",
  "Catawba",
  "Chattooga",
  "Chauga",
  "Chechessee",
  "Combahee",
  "Colleton",
  "Congaree",
  "Cooper",
  "Coosaw",
  "Coosawhatchie",
  "Dead",
  "East Fork Chatooga",
  "Edisto",
  "Enoree",
  "Flat Shoals",
  "Four Holes",
  "Gills",
  "Great Pee Dee",
  "Harbor",
  "Horsepasture",
  "Keowee",
  "Little Lynches",
  "Little Pee Dee",
  "Little Salkehatchie",
  "Little Saluda",
  "Little Sandy",
  "Lumber",
  "Lynches",
  "May",
  "Morgan",
  "New",
  "Oolenoy",
  "Okatee",
  "Old Dead",
  "Pacolet",
  "Pocotaligo",
  "Reedy",
  "Rocky",
  "Salkehatchie",
  "Saluda",
  "Sampit",
  "Sandy",
  "Santee",
  "Savannah",
  "Seneca",
  "Stevens",
  "Stono",
  "Story",
  "Thompson",
  "Toxaway",
  "Tugaloo",
  "Tyger",
  "Waccamaw",
  "Wando",
  "Wateree",
  "Whitewater",
  "Wright",
  "Alligator",
  "Ararat",
  "Black",
  "Broad",
  "Cane",
  "Cape Fear",
  "Cashie",
  "Catawba",
  "Cheoah",
  "Chowan",
  "Coleman",
  "Cullasaja",
  "Dan",
  "Davidson",
  "Deep",
  "Elk",
  "Eno",
  "First Broad",
  "Fisher",
  "French Broad",
  "Great Pee Dee",
  "Great Coharie",
  "Green",
  "Haw",
  "Henry Fork",
  "Hungry",
  "Hyco",
  "Jacob Fork",
  "Johns",
  "Linville",
  "Little Coharie",
  "Little Fisher",
  "Little Hungry",
  "Little Tennessee",
  "Little Uwharrie",
  "Lockwood Folly",
  "Lower Little",
  "Lumber",
  "Lynches",
  "Mayo",
  "Meherrin",
  "Middle Little",
  "Mills",
  "Mitchell",
  "Nantahala",
  "Neuse",
  "New Hope",
  "New",
  "Nolichucky",
  "North Toe",
  "Nottely",
  "North Pacolet",
  "North",
  "Northeast Cape Fear",
  "Pamlico",
  "Pasquotank",
  "Pee Dee",
  "Perquimans",
  "Pigeon",
  "Reddies",
  "Roanoke",
  "Roaring",
  "Rocky",
  "Rough Butt",
  "Scuppernong",
  "Second Broad",
  "Shallotte",
  "Six Run",
  "South Fork Catawba",
  "South",
  "South Toe",
  "South Yadkin",
  "Swannanoa",
  "Tar",
  "Trent",
  "Tuckasegee",
  "Upper Little",
  "Uwharrie",
  "Waccamaw",
  "Watauga",
  "White Oak",
  "Whitewater",
  "Wiccacon",
  "Yadkin",
  "Aarons",
  "Abrams",
  "Accokeek",
  "Accotink",
  "Allen",
  "Appomattox",
  "Aquia",
  "Ararat",
  "Back",
  "Back",
  "Bailey",
  "Banister",
  "Beaver",
  "Beaverdam",
  "Bennett",
  "Big Chestnut",
  "Big",
  "Big Horse",
  "Big Moccasin",
  "Big Otter",
  "Big Reed",
  "Blackwater",
  "Bluestone",
  "Bluestone",
  "Brewers",
  "Briery",
  "Broad",
  "Browns Dan",
  "Buck",
  "Buffalo",
  "Bull",
  "Bullpasture",
  "Burke",
  "Bush",
  "Byrd",
  "Cabin",
  "Cameron",
  "Cascade",
  "Catawba",
  "Catoctin",
  "Calfpasture",
  "Cat Point",
  "Cedar",
  "Chickahominy",
  "Chopawamsic",
  "Chestnut",
  "Christians",
  "Chuckatuck",
  "Clinch",
  "Coan",
  "Cockle",
  "Cold Spring",
  "College",
  "Conway",
  "Cooks",
  "Copper",
  "Corrotoman",
  "Country Line",
  "Covington",
  "Cowpasture",
  "Craig",
  "Cranes Nest",
  "Cripple",
  "Crooked",
  "Cub",
  "Cub",
  "Dan",
  "David",
  "Deep",
  "Diascund",
  "Difficult",
  "Dismal",
  "Dogue",
  "Doyles",
  "Dreaming",
  "Dry",
  "Dry",
  "Dunlap",
  "East Little Seneca",
  "East",
  "Eastern Branch Elizabeth",
  "Elizabeth",
  "Elk",
  "Falling",
  "Fisher",
  "Flat",
  "Flat Rock",
  "Fountains",
  "Four Mile",
  "Fox",
  "German",
  "Goose",
  "Grassy",
  "Grays",
  "Great Wicomico",
  "Guest",
  "Hampton",
  "Hardware",
  "Harris",
  "Harris",
  "Hawksbill",
  "Hays",
  "Hazel",
  "Helton",
  "Hogue",
  "Home",
  "Hoskins",
  "Hughes",
  "Hull",
  "Hunting",
  "Hyco",
  "Indian",
  "Indian",
  "Irish",
  "Isaacs",
  "Island",
  "Ivy",
  "Jackson",
  "James",
  "Johns",
  "Jordan",
  "Kerrs",
  "Kettle",
  "Kimberling",
  "Knotts",
  "Knox",
  "Lafayette",
  "Laurel",
  "Laurel",
  "Lawnes",
  "Leatherwood",
  "Levisa",
  "Linville",
  "Little Back",
  "Little Bluestone",
  "Little Bull",
  "Little Calfpasture",
  "Little Dan",
  "Little Dry",
  "Little Falling",
  "Little Hunting",
  "Little Nottoway",
  "Little Otter",
  "Little Piney",
  "Little Reed Island",
  "Little",
  "Little Walker",
  "Little Wicomico",
  "Little Willis",
  "Lovills",
  "Lower Machodoc",
  "Lynch",
  "Lynnhaven",
  "McClure",
  "Machipongo",
  "Maggodee",
  "Maracossic",
  "Martin",
  "Mat",
  "Matta",
  "Mattaponi",
  "Mattox",
  "Maury",
  "Mayo",
  "Mayo",
  "Mechums",
  "Mechunk",
  "Meherrin",
  "Middle Fork Holston",
  "Middle Meherrin",
  "Middle",
  "Mill",
  "Mine",
  "Mollys",
  "Moormans",
  "Mosquito",
  "Motto",
  "Mountain",
  "Muddy",
  "Naked",
  "Namozine",
  "Nansemond",
  "Neabsco",
  "Negro",
  "New",
  "Newfound",
  "Ni",
  "Nomini",
  "North Anna",
  "North Buffalo",
  "North Fork Catoctin",
  "North Fork Clinch",
  "North Fork Goose",
  "North Fork Holston",
  "North Fork Powell",
  "North Fork Rivanna",
  "North Fork Roanoke",
  "North Fork Shenandoah",
  "North Fork Tye",
  "North Landing",
  "North Mayo",
  "North Meherrin",
  "North",
  "Northwest",
  "Northwest Yeocomico",
  "Nottoway",
  "Occoquan",
  "Occupacia",
  "Ogle",
  "Opequon",
  "Pagan",
  "Pamunkey",
  "Pamunkey",
  "Passage",
  "Peak",
  "Pedlar",
  "Perrin",
  "Piankatank",
  "Pigg",
  "Pimmit",
  "Piney",
  "Piscataway",
  "Po",
  "Pocaty",
  "Pocomoke",
  "Pohick",
  "Poni",
  "Popes",
  "Popes Head",
  "Poquoson",
  "Poropotank",
  "Possum",
  "Potomac",
  "Potomac",
  "Potts",
  "Pound",
  "Powell",
  "Powhite",
  "Quantico",
  "Queen",
  "Rapidan",
  "Rappahannock",
  "Reed",
  "Reed Island",
  "Reedy",
  "Rivanna",
  "Roach",
  "Roanoke",
  "Roanoke",
  "Robinson",
  "Rockfish",
  "Rose",
  "Rosier",
  "Rowanty",
  "Rucker",
  "Rush",
  "Russell",
  "Russell",
  "Saint Marys",
  "Sandy",
  "Sandy",
  "Sappony",
  "Seneca",
  "Severn",
  "Shenandoah",
  "Shoemaker",
  "Sinking",
  "Skiffes",
  "Slate",
  "Slate",
  "Sleepy",
  "Smith",
  "Smith",
  "Snake",
  "Snow",
  "Somerton",
  "South Anna",
  "Stave",
  "South Branch Potomac",
  "South Buffalo",
  "South Fork Catoctin",
  "South Fork Clinch",
  "South Fork Elizabeth",
  "South Fork Falling",
  "South Fork Holston",
  "South Fork Powell",
  "South Fork Rivanna",
  "South Fork Roanoke",
  "South Fork Shenandoah",
  "South Fork South Branch Potomac",
  "South Fork Tye",
  "South Mayo",
  "South Meherrin",
  "South",
  "South Yeocomico",
  "Southern Branch Elizabeth",
  "Staunton",
  "Stewarts",
  "Stinking",
  "Stock",
  "Stony",
  "Straightstone",
  "Stuart",
  "Sugarland",
  "Swift",
  "Ta",
  "Taylors",
  "Tear Wallet",
  "Thornton",
  "Three",
  "Tinker",
  "Totuskey",
  "Tug",
  "Tye",
  "Upper Chippokes",
  "Upper Machodoc",
  "Walker",
  "Wallen",
  "Wards",
  "Ware",
  "Warwick",
  "West Fork Little",
  "West Little Seneca",
  "West Yeocomico",
  "Western Branch Elizabeth",
  "Whistle",
  "Whitetop Laurel",
  "Willis",
  "Wilson",
  "Wolf",
  "Yeocomico",
  "York",
  "Alloway",
  "Anacostia",
  "Antietam",
  "Back",
  "Ballenger",
  "Bear",
  "Bennett",
  "Big Annemessex",
  "Big Hunting",
  "Big Pipe",
  "Bird",
  "Blackwater",
  "Bodkin",
  "Bread and Cheese",
  "Broad",
  "Broad",
  "Budds",
  "Bush",
  "Bush",
  "Casselman",
  "Cabin John",
  "Carroll",
  "Catoctin",
  "Chester",
  "Chicamuxen",
  "Choptank",
  "Christina",
  "Conococheague",
  "Cuckold",
  "Curtis",
  "Deer",
  "Deep",
  "Difficult",
  "Dividing",
  "Double Pipe",
  "Dry Seneca",
  "Dueling",
  "Dundee",
  "Elk",
  "Evitts",
  "Fifteenmile",
  "Fishing",
  "Flintstone",
  "Frog Mortar",
  "Furnace",
  "Georges",
  "Great Seneca",
  "Gunpowder",
  "Gunpowder",
  "Gwynns",
  "Hawlings",
  "Harris",
  "Henson",
  "Herring",
  "Horsepen",
  "Indian",
  "Israel",
  "Jones",
  "Laurel",
  "Licking",
  "Limekiln",
  "Linganore",
  "Little Catoctin",
  "Little Choptank",
  "Little Conococheague",
  "Little Falls",
  "Little Gunpowder",
  "Little Hunting",
  "Little Monocacy",
  "Little Paint",
  "Little Patuxent",
  "Little Pipe",
  "Little Seneca",
  "Little Tuscarora",
  "Little Youghiogheny",
  "Lyons",
  "Magothy",
  "Marley",
  "Marsh",
  "Marshyhope",
  "Mattawoman",
  "Middle",
  "Middle Patuxent",
  "Middle",
  "Minnehaha",
  "Monocacy",
  "Moores",
  "Muddy",
  "Nanjemoy",
  "Nanticoke",
  "North Branch Patapsco",
  "North Branch Potomac",
  "North East",
  "Northeast Branch Anacostia",
  "Northwest Branch Anacostia",
  "Northwest Branch Patapsco",
  "Octoraro",
  "Oxon",
  "Owens",
  "Paint",
  "Patapsco",
  "Patuxent",
  "Piscataway",
  "Pocomoke",
  "Pomonkey",
  "Popes",
  "Port Tobacco",
  "Potomac",
  "Principio",
  "Rhode",
  "Rock",
  "Rock",
  "St. Marys",
  "Saltpeter",
  "Sams",
  "Sassafras",
  "Savage",
  "Seneca",
  "Severn",
  "Sideling Hill",
  "Sligo",
  "South Branch Patapsco",
  "South",
  "Stony",
  "Susquehanna",
  "Swanson",
  "Tenmile",
  "Toms",
  "Tonoloway",
  "Town",
  "Tuckahoe",
  "Tuscarora",
  "Watts",
  "West",
  "Western",
  "Western Branch Patuxent",
  "Wicomico",
  "Wills",
  "Winters",
  "Wye",
  "Youghiogheny",
  "Appoquinimink",
  "Blackbird",
  "Brandywine",
  "Broadkill",
  "Choptank",
  "Christina",
  "Delaware",
  "Hershey",
  "Indian",
  "Leipsic",
  "Lingo",
  "Little",
  "Marshyhope",
  "Mill",
  "Mispillion",
  "Murderkill",
  "Naamans",
  "Nanticoke",
  "Pepper",
  "Pocomoke",
  "Red Clay",
  "St. Jones",
  "Sassafras",
  "Shellpot",
  "Simons",
  "Smyrna",
  "White Clay",
  "Abbots",
  "Albertson",
  "Alloway",
  "Ambrose",
  "Arthur",
  "Assiscunk",
  "Assunpink",
  "Back",
  "Baldwins",
  "Ballanger",
  "Bass",
  "Batsto",
  "Bear",
  "Bear",
  "Beaver",
  "Beaverdam",
  "Beden",
  "Berrys",
  "Big Flat",
  "Big Graveling",
  "Big Timber",
  "Birch Swamp",
  "Bisphams Mill",
  "Black",
  "Black",
  "Black",
  "Blue",
  "Bonygutt",
  "Bound",
  "Branch Back",
  "Burrs Mill",
  "Canoe",
  "Carters",
  "Cat Tail",
  "Cedar",
  "Cedar",
  "Cedar Swamp",
  "Clove",
  "Cohansey",
  "Cooper",
  "Cory's",
  "Crab",
  "Cranbury",
  "Cross",
  "Crosswicks",
  "Cruser",
  "Cow Yard",
  "Dead",
  "Deep Voll",
  "Deepavaal",
  "Deep Run",
  "Delaware",
  "Dennis",
  "Devils",
  "Diamond",
  "Dividing",
  "Duck Pond",
  "Dwars",
  "East",
  "Elizabeth",
  "English",
  "Fenwick",
  "First",
  "Flat",
  "Fleischer",
  "Foulerton's",
  "Friendship",
  "Game",
  "Goffle",
  "Great",
  "Great",
  "Great Egg Harbor",
  "Great Swamp",
  "Green",
  "Greenwood ",
  "Hackensack ",
  "Hakihokake ",
  "Harihokake ",
  "Harrys ",
  "Heathcote ",
  "Heathcote Brook ",
  "Honey ",
  "Ho-Ho-Kus ",
  "Holland ",
  "Hospitality ",
  "Hudson ",
  "Indian Grove ",
  "Ireland ",
  "Kill Van ",
  "Lamington ",
  "Landing ",
  "Lawrence ",
  "Lewis ",
  "Little Bear ",
  "Little Diamond ",
  "Little Egg Harbor ",
  "Little Flat ",
  "Lockatong ",
  "Lopatcong",
  "Lubbers",
  "Mahwah",
  "Manalapan",
  "Manantico",
  "Manasquan",
  "Mannington",
  "Mantua",
  "Manumuskin",
  "Marshes",
  "Matawan",
  "Matchaponix",
  "Maurice",
  "Metedeconk",
  "Middle",
  "Middlebush",
  "Mill",
  "Mile",
  "Millstone",
  "Molly Ann",
  "Mount Misery",
  "Morses",
  "Muddy",
  "Mullica",
  "Musconetcong",
  "Muskee",
  "Musquapsink",
  "Naakpunkt",
  "Nantuxent",
  "Navesink",
  "Neepaulakating",
  "Negro",
  "Nescochague",
  "Neshanic",
  "Nine Mile",
  "Nishayne",
  "Nishisakawick",
  "Nomahegan",
  "North Branch Metedeconk",
  "North Branch Rancocas",
  "North Branch Raritan",
  "North",
  "Oakeys",
  "Ogden",
  "Oldmans",
  "Oranoaken",
  "Oswego",
  "Overpeck",
  "Oyster",
  "Papakating",
  "Parrow",
  "Pascack",
  "Passaic",
  "Paulins",
  "Peckman",
  "Penns",
  "Pennsauken",
  "Pequannock",
  "Pequest",
  "Peters",
  "Pike",
  "Pine Tree",
  "Pochuck",
  "Pohatcong",
  "Pole Bridge",
  "Pompton",
  "Pump",
  "Punkhorn",
  "Raccoon",
  "Rahway",
  "Ramapo",
  "Randolph",
  "Rancocas",
  "Raritan",
  "Ridgeway",
  "Roaring",
  "Roaring",
  "Rock",
  "Rockaway",
  "Rockaway",
  "Rocky",
  "Royce",
  "Saddle",
  "Salem",
  "Sawmill",
  "Scotland",
  "Second",
  "Shabakunk",
  "Shallow",
  "Shark",
  "Shrewsbury",
  "Simonson",
  "Six Mile",
  "Slippery Rock",
  "Slough",
  "Sluice",
  "Smith",
  "South Branch Metedeconk",
  "South Branch Rancocas",
  "South Branch Raritan",
  "South",
  "Southwest Branch Rancocas",
  "Sparkill",
  "Spring Garden",
  "Squaw",
  "Steep Hill",
  "Stephen",
  "Stevenson",
  "Still",
  "Stony",
  "Stony Brook",
  "Stow",
  "Sucker",
  "Swimming",
  "Ten Mile",
  "Terhune",
  "Third",
  "Timber",
  "Toms",
  "Toney's",
  "Tuckahoe",
  "Tulpehocken",
  "Turtle",
  "Union",
  "Wading",
  "Wallkill",
  "Wanaque",
  "Wawayanda",
  "West Branch Wading",
  "West",
  "Westecunk",
  "Whippany",
  "Wickecheoke",
  "Wigwam",
  "Woodbridge",
  "Woodbury",
  "Woodsville",
  "Yantacaw",
  "Yellow",
  "Abbie",
  "Alabama",
  "Alamuchee",
  "Alligator",
  "Anderson",
  "Apalachee",
  "Autauga",
  "Barbour",
  "Bashi",
  "Bassett",
  "Bassetts",
  "Bates",
  "Bay Minette",
  "Bayou",
  "Bayou la",
  "Bayou",
  "Bayou",
  "Bear",
  "Beaver",
  "Bennett",
  "Benson",
  "Big Bayou",
  "Big Black",
  "Big Brush",
  "Big Canoe",
  "Big Coldwater",
  "Big Coon",
  "Big Creek",
  "Big Escambia",
  "Big Flat",
  "Big Juniper",
  "Big Lizard",
  "Big Nance",
  "Big Prairie",
  "Big Sandy",
  "Big Spring",
  "Big Swamp",
  "Big Tallawampa",
  "Big Wills",
  "Big Yellow",
  "Bilbo",
  "Black Warrior",
  "Blackburn Fork Little Warrior",
  "Blackwater",
  "Blackwater",
  "Blakeley",
  "Blevens",
  "Blue",
  "Blue Spring",
  "Bluewater",
  "Bodka",
  "Bogue Chitto",
  "Bolton",
  "Bon Secour",
  "Borden",
  "Brier Fork Flint",
  "Broglan",
  "Broglen",
  "Brush",
  "Brushy",
  "Buck",
  "Bull Mountain",
  "Burnt Corn",
  "Butler",
  "Buttahatchee",
  "Buxahatchee",
  "Buzzard Roost",
  "Cahaba",
  "Calebee",
  "Callaway",
  "Calvert Prong Little Warrior",
  "Cane",
  "Caney",
  "Capsey",
  "Catoma",
  "Cedar",
  "Chaney",
  "Chatahospee",
  "Chattahoochee",
  "Chattooga",
  "Cheaha",
  "Cheneyhatchee",
  "Chestnut",
  "Chewalla",
  "Chickasaw",
  "Chickasaw",
  "Chilatchee",
  "Choccolocco",
  "Choctawhatchee",
  "Chubbehatchee",
  "Claybank",
  "Clear",
  "Conecuh",
  "Conway",
  "Coon",
  "Coosa",
  "Cornhouse",
  "Cotaco",
  "Cotohaga",
  "Cottonford",
  "Cowikee",
  "Cowpen",
  "Crab",
  "Crooked",
  "Crow",
  "Cubahatchee",
  "Cypress",
  "Davis",
  "Dixon",
  "Dog",
  "Double Bridges",
  "Dry",
  "Duck",
  "Dykes",
  "East Fork Choctawhatchee",
  "East Fork Little",
  "East Fowl",
  "Eightmile",
  "Elk",
  "Emauhee",
  "Emuckfaw",
  "Enitachopco",
  "Escambia",
  "Escatawpa",
  "Eslava",
  "Estill",
  "Fish",
  "Five Runs",
  "Fivemile",
  "Flat",
  "Flint",
  "Flint",
  "Fowl",
  "Goose",
  "Grant",
  "Gum",
  "Gunnison",
  "Gurley",
  "Halawakee",
  "Hall",
  "Halls Mill",
  "Hammock",
  "Harbuck",
  "Hatchechubbee",
  "Hatchet",
  "Heron",
  "High Pine",
  "Hill",
  "Hillabahatchee",
  "Hillabee",
  "Hollinger",
  "Holmes",
  "Horse",
  "Huntsville Spring",
  "Hurricane",
  "Indian",
  "Ivy",
  "Jackson",
  "Jones",
  "Judy",
  "Kelly",
  "Kinterbish",
  "Kirby",
  "Lightwood Knot",
  "Limestone",
  "Lindsey",
  "Line",
  "Little Bear",
  "Little Cahaba",
  "Little Choctawhatchee",
  "Little",
  "Little Cypress",
  "Little Hillabee",
  "Little Lizard",
  "Little Mulberry",
  "Little New",
  "Little",
  "Little",
  "Little Tallapoosa",
  "Little Tallawampa",
  "Little Uchee",
  "Little Warrior",
  "Little Weoka",
  "Locust",
  "Long Island",
  "Lookout",
  "Lost",
  "Lower Crab",
  "Lubbub",
  "Luxapallila",
  "Magnolia",
  "Mahan",
  "Majors",
  "Mayo Mill",
  "Middle Fork Cowikee",
  "Middle Fork Deer",
  "Middle",
  "Miflin",
  "Mill",
  "Mills",
  "Minter",
  "Mobile",
  "Moore",
  "Mortar",
  "Mountain",
  "Mud",
  "Muddy",
  "Mulberry",
  "Mulberry",
  "Murder",
  "Muscadine",
  "Mush",
  "Nances",
  "New",
  "No Business",
  "North Fork Cowikee",
  "North Fork Deer",
  "North",
  "North Sauty",
  "Noxubee",
  "Oak",
  "Oakmulgee",
  "Ohatchee",
  "Okatuppa",
  "Old Town",
  "Omusee",
  "Osanippa",
  "Oseligee",
  "Paint",
  "Paint Rock",
  "Palmetto",
  "Patsaliga",
  "Patton",
  "Pea",
  "Peckerwood",
  "Perch",
  "Perdido",
  "Pine Barren",
  "Piney",
  "Piney Woods",
  "Pintlala",
  "Pond",
  "Portage",
  "Pursley",
  "Puss Cuss",
  "Rabbit",
  "Raft",
  "Rambo",
  "Rattlesnake",
  "Right Fork Clear",
  "Robinson",
  "Robinson",
  "Rock",
  "Rush",
  "Ryan",
  "Sand",
  "Sandy",
  "Santa Bogue",
  "Scarham",
  "Schultz",
  "Second",
  "Sepulga",
  "Shades",
  "Shirtee",
  "Shoal",
  "Silas",
  "Sipsey",
  "Sipsey",
  "Sipsey",
  "Slab",
  "Soapstone",
  "Socapatoy",
  "Soldier",
  "South Fork Cowikee",
  "South Fork Deer",
  "South Sauty",
  "Souwilpa",
  "Spanish",
  "Spring",
  "Sturdivant",
  "Styx",
  "Sucarbowa",
  "Sucarnoochee",
  "Sugar",
  "Swamp",
  "Sweetwater",
  "Swift",
  "Talladega",
  "Tallapoosa",
  "Tallaseehatchee",
  "Tallawassee",
  "Tennessee",
  "Tensaw",
  "Terrapin",
  "Threemile",
  "Tombigbee",
  "Town",
  "Trussells",
  "Tuckabum",
  "Turkey",
  "Uchee",
  "Uphapee",
  "Valley",
  "Village",
  "Wacoochee",
  "Wahalak",
  "Walnut",
  "Waxahatchee",
  "Wedowee",
  "Wehadkee",
  "Weogufka",
  "Weoka",
  "Wesobulga",
  "West Flint",
  "West Fork Choctawhatchee",
  "West Fork Little",
  "West Fowl",
  "West",
  "Whitewater",
  "Wrights",
  "Widows",
  "Wolf",
  "Woodward",
  "Yantley",
  "Yellow",
  "Yellow Leaf",
  "Yellow",
  "Yellowleaf",
]

export const riverTitles = [
  "River",
  "Canal",
  "Creek",
  "Channel",
  "Tributary",
  "Waterway",
  "Branch",
  "",
  "Watercourse",
  "Run",
  "Stream",
  "Branch",
  "Brook",
  "Fork"
]
