export const riverNameDictionary = [
  "Amielia",
  "Belis",
  "Nassau",
  "South",
  "Thomas",
  "Fort George",
  "Saint Mary",
  "Saint John",
  "Sisters",
  "Broward",
  "Trout",
  "Ribault",
  "Little Trout",
  "Arlington",
  "Pottsburg",
  "Ortega",
  "Cedar",
  "Julington",
  "Black",
  "Rice",
  "Dunns",
  "Ocklawaha",
  "Orange",
  "Styx",
  "Cross",
  "Silver",
  "Haines",
  "Dead",
  "Palatlakaha",
  "Salt Springs",
  "Alexander Springs",
  "Hontoon",
  "Wekiva",
  "Blackwater",
  "Econlockhatchee",
  "Tolomato",
  "San Sebastian",
  "Halifax",
  "Spruce",
  "Tomoka",
  "Banana",
  "Elbow",
  "Crane",
  "Turkey",
  "Saint Lucie",
  "Loxahatchee",
  "Hillsboro",
  "Stranahan",
  "New",
  "Middle",
  "Oleta",
  "Miami",
  "Bivens",
  "Tumbling",
  "Sweetwater",
  "Prairie",
  "Newnan",
  "Hatchet",
  "Forest",
  "Chacala",
  "Sawgrass",
  "Wauburg",
  "Burnt",
  "Dog",
  "Fisheating",
  "Kissimmee",
  "Reedy",
  "Bonnet",
  "Cypress",
  "Taylor",
  "Joe",
  "Shark",
  "Harney",
  "Broad",
  "Rodgers",
  "Lostman",
  "Chatham",
  "Huston",
  "Lopez",
  "Turner",
  "Barron",
  "Fakahatchee",
  "Whitney",
  "Caloosahatchee",
  "Estero",
  "Peace",
  "Myakka",
  "Manatee",
  "Anclote",
  "Weeki Watchee",
  "Homosassa",
  "Withlacoochee",
  "Waccasassa",
  "Suwannee",
  "Ichetucknee",
  "Alapatha",
  "Steinhatchee",
  "Fenholloway",
  "Econtina",
  "Aucilla",
  "Ochlockonee",
  "Crooked",
  "Carrabelle",
  "Econtina",
  "Chattahoochee",
  "East Bay",
  "Yellow",
  "Escambia",
  "Perdido",
  "Alabaha",
  "Alan",
  "Alapaha",
  "Alapahoochee",
  "Alcovy",
  "Alley",
  "Allez",
  "Alligator",
  "Altamaha",
  "Apalachee",
  "Aucilla",
  "Bear",
  "Beech",
  "Belfast",
  "Big Satilla",
  "Big Satilla",
  "Black",
  "Black",
  "Black",
  "Brier",
  "Broad",
  "Broro",
  "Brunswick",
  "Buffalo",
  "Bull",
  "Bull",
  "Camp",
  "Caney",
  "Canoochee",
  "Cartecay",
  "Chattahoochee",
  "Chattooga",
  "Chattooga",
  "Chestatee",
  "Coleman",
  "Coleoatchee",
  "Conasauga",
  "Coosa",
  "Coosawattee",
  "Crescent",
  "Crooked",
  "Crooked",
  "Cumberland",
  "Darien",
  "Deep",
  "Dog",
  "Duplin",
  "Ebenezer",
  "Ellijay",
  "Etowah",
  "Flat Shoal",
  "Flint",
  "Foe Killer",
  "Frederica",
  "Gum Swamp",
  "Halfmoon",
  "Hampton",
  "Hannahatchee",
  "Hazel",
  "Herb",
  "Hiwassee",
  "Hog Wallow",
  "Hudson",
  "Ichawaynochaway",
  "Jacks",
  "Jerico",
  "Johns",
  "Johns",
  "Kettle",
  "Kinchafoonee",
  "Knoxboro",
  "Laurel View",
  "Law",
  "Liberty",
  "Lick Log",
  "Little Hazel",
  "Little Ochlockonee",
  "Little Ocmulgee",
  "Little Ogeechee",
  "Little Ogeechee",
  "Little Ohoopee",
  "Little Satilla",
  "Little Satilla",
  "Little Tallapoosa",
  "Little Tennessee",
  "Mackay",
  "Medway",
  "Middle Oconee",
  "Mountain Oak",
  "Muckalee",
  "Mud",
  "Mulberry",
  "Mulberry",
  "Nancy",
  "New",
  "New",
  "Noonday",
  "North Newport",
  "North Oconee",
  "North",
  "North",
  "Noses",
  "Nottely",
  "Ochlockonee",
  "Ocmulgee",
  "Oconee",
  "Odingsell",
  "Ogeechee",
  "Ohoopee",
  "Okapilco",
  "Oostanaula",
  "Pataula",
  "Peachtree",
  "Styx",
  "Rocky Comfort",
  "Runaway Negro",
  "Saint Mary",
  "Sapelo",
  "Satilla",
  "Savannah",
  "Sawhatchee",
  "Sewell Mill",
  "Shad",
  "Shoal",
  "Sixteen Mile",
  "Skidaway",
  "Sope",
  "Soquee",
  "South Newport",
  "South",
  "Spring",
  "Suwannee",
  "Suwannoochee",
  "Sweetwater",
  "Swift",
  "Tallapoosa",
  "Tallulah",
  "Tesnatee",
  "Tivoli",
  "Tobesofkee",
  "Toccoa",
  "Towaliga",
  "Tugaloo",
  "Turtle",
  "Upatoi",
  "Vernon",
  "Vickery",
  "Willacoochee",
  "Willeo",
  "Williamson",
  "Wilmington",
  "Withlacoochee",
  "Yellow",
  "Yellowjacket",
  "Ashepoo",
  "Ashley",
  "Back",
  "Bates Old",
  "Beaufort",
  "Black",
  "Black Mingo",
  "Broad",
  "Broad",
  "Bull Swamp",
  "Bush",
  "Catawba",
  "Chattooga",
  "Chauga",
  "Chechessee",
  "Combahee",
  "Colleton",
  "Congaree",
  "Cooper",
  "Coosaw",
  "Coosawhatchie",
  "Dead",
  "East Fork Chatooga",
  "Edisto",
  "Enoree",
  "Flat Shoals",
  "Four Holes",
  "Gills",
  "Great Pee Dee",
  "Harbor",
  "Horsepasture",
  "Keowee",
  "Little Lynches",
  "Little Pee Dee",
  "Little Salkehatchie",
  "Little Saluda",
  "Little Sandy",
  "Lumber",
  "Lynches",
  "May",
  "Morgan",
  "New",
  "Oolenoy",
  "Okatee",
  "Old Dead",
  "Pacolet",
  "Pocotaligo",
  "Reedy",
  "Rocky",
  "Salkehatchie",
  "Saluda",
  "Sampit",
  "Sandy",
  "Santee",
  "Savannah",
  "Seneca",
  "Stevens",
  "Stono",
  "Story",
  "Thompson",
  "Toxaway",
  "Tugaloo",
  "Tyger",
  "Waccamaw",
  "Wando",
  "Wateree",
  "Whitewater",
  "Wright",
  "Alligator",
  "Ararat",
  "Black",
  "Broad",
  "Cane",
  "Cape Fear",
  "Cashie",
  "Catawba",
  "Cheoah",
  "Chowan",
  "Coleman",
  "Cullasaja",
  "Dan",
  "Davidson",
  "Deep",
  "Elk",
  "Eno",
  "First Broad",
  "Fisher",
  "French Broad",
  "Great Pee Dee",
  "Great Coharie",
  "Green",
  "Haw",
  "Henry Fork",
  "Hungry",
  "Hyco",
  "Jacob Fork",
  "Johns",
  "Linville",
  "Little Coharie",
  "Little Fisher",
  "Little Hungry",
  "Little Tennessee",
  "Little Uwharrie",
  "Lockwood Folly",
  "Lower Little",
  "Lumber",
  "Lynches",
  "Mayo",
  "Meherrin",
  "Middle Little",
  "Mills",
  "Mitchell",
  "Nantahala",
  "Neuse",
  "New Hope",
  "New",
  "Nolichucky",
  "North Toe",
  "Nottely",
  "North Pacolet",
  "North",
  "Northeast Cape Fear",
  "Pamlico",
  "Pasquotank",
  "Pee Dee",
  "Perquimans",
  "Pigeon",
  "Reddies",
  "Roanoke",
  "Roaring",
  "Rocky",
  "Rough Butt",
  "Scuppernong",
  "Second Broad",
  "Shallotte",
  "Six Run",
  "South Fork Catawba",
  "South",
  "South Toe",
  "South Yadkin",
  "Swannanoa",
  "Tar",
  "Trent",
  "Tuckasegee",
  "Upper Little",
  "Uwharrie",
  "Waccamaw",
  "Watauga",
  "White Oak",
  "Whitewater",
  "Wiccacon",
  "Yadkin",
  "Aarons",
  "Abrams",
  "Accokeek",
  "Accotink",
  "Allen",
  "Appomattox",
  "Aquia",
  "Ararat",
  "Back",
  "Back",
  "Bailey",
  "Banister",
  "Beaver",
  "Beaverdam",
  "Bennett",
  "Big Chestnut",
  "Big",
  "Big Horse",
  "Big Moccasin",
  "Big Otter",
  "Big Reed",
  "Blackwater",
  "Bluestone",
  "Bluestone",
  "Brewers",
  "Briery",
  "Broad",
  "Browns Dan",
  "Buck",
  "Buffalo",
  "Bull",
  "Bullpasture",
  "Burke",
  "Bush",
  "Byrd",
  "Cabin",
  "Cameron",
  "Cascade",
  "Catawba",
  "Catoctin",
  "Calfpasture",
  "Cat Point",
  "Cedar",
  "Chickahominy",
  "Chopawamsic",
  "Chestnut",
  "Christians",
  "Chuckatuck",
  "Clinch",
  "Coan",
  "Cockle",
  "Cold Spring",
  "College",
  "Conway",
  "Cooks",
  "Copper",
  "Corrotoman",
  "Country Line",
  "Covington",
  "Cowpasture",
  "Craig",
  "Cranes Nest",
  "Cripple",
  "Crooked",
  "Cub",
  "Cub",
  "Dan",
  "David",
  "Deep",
  "Diascund",
  "Difficult",
  "Dismal",
  "Dogue",
  "Doyles",
  "Dreaming",
  "Dry",
  "Dry",
  "Dunlap",
  "East Little Seneca",
  "East",
  "Eastern Branch Elizabeth",
  "Elizabeth",
  "Elk",
  "Falling",
  "Fisher",
  "Flat",
  "Flat Rock",
  "Fountains",
  "Four Mile",
  "Fox",
  "German",
  "Goose",
  "Grassy",
  "Grays",
  "Great Wicomico",
  "Guest",
  "Hampton",
  "Hardware",
  "Harris",
  "Harris",
  "Hawksbill",
  "Hays",
  "Hazel",
  "Helton",
  "Hogue",
  "Home",
  "Hoskins",
  "Hughes",
  "Hull",
  "Hunting",
  "Hyco",
  "Indian",
  "Indian",
  "Irish",
  "Isaacs",
  "Island",
  "Ivy",
  "Jackson",
  "James",
  "Johns",
  "Jordan",
  "Kerrs",
  "Kettle",
  "Kimberling",
  "Knotts",
  "Knox",
  "Lafayette",
  "Laurel",
  "Laurel",
  "Lawnes",
  "Leatherwood",
  "Levisa",
  "Linville",
  "Little Back",
  "Little Bluestone",
  "Little Bull",
  "Little Calfpasture",
  "Little Dan",
  "Little Dry",
  "Little Falling",
  "Little Hunting",
  "Little Nottoway",
  "Little Otter",
  "Little Piney",
  "Little Reed Island",
  "Little",
  "Little Walker",
  "Little Wicomico",
  "Little Willis",
  "Lovills",
  "Lower Machodoc",
  "Lynch",
  "Lynnhaven",
  "McClure",
  "Machipongo",
  "Maggodee",
  "Maracossic",
  "Martin",
  "Mat",
  "Matta",
  "Mattaponi",
  "Mattox",
  "Maury",
  "Mayo",
  "Mayo",
  "Mechums",
  "Mechunk",
  "Meherrin",
  "Middle Fork Holston",
  "Middle Meherrin",
  "Middle",
  "Mill",
  "Mine",
  "Mollys",
  "Moormans",
  "Mosquito",
  "Motto",
  "Mountain",
  "Muddy",
  "Naked",
  "Namozine",
  "Nansemond",
  "Neabsco",
  "Negro",
  "New",
  "Newfound",
  "Ni",
  "Nomini",
  "North Anna",
  "North Buffalo",
  "North Fork Catoctin",
  "North Fork Clinch",
  "North Fork Goose",
  "North Fork Holston",
  "North Fork Powell",
  "North Fork Rivanna",
  "North Fork Roanoke",
  "North Fork Shenandoah",
  "North Fork Tye",
  "North Landing",
  "North Mayo",
  "North Meherrin",
  "North",
  "Northwest",
  "Northwest Yeocomico",
  "Nottoway",
  "Occoquan",
  "Occupacia",
  "Ogle",
  "Opequon",
  "Pagan",
  "Pamunkey",
  "Pamunkey",
  "Passage",
  "Peak",
  "Pedlar",
  "Perrin",
  "Piankatank",
  "Pigg",
  "Pimmit",
  "Piney",
  "Piscataway",
  "Po",
  "Pocaty",
  "Pocomoke",
  "Pohick",
  "Poni",
  "Popes",
  "Popes Head",
  "Poquoson",
  "Poropotank",
  "Possum",
  "Potomac",
  "Potomac",
  "Potts",
  "Pound",
  "Powell",
  "Powhite",
  "Quantico",
  "Queen",
  "Rapidan",
  "Rappahannock",
  "Reed",
  "Reed Island",
  "Reedy",
  "Rivanna",
  "Roach",
  "Roanoke",
  "Roanoke",
  "Robinson",
  "Rockfish",
  "Rose",
  "Rosier",
  "Rowanty",
  "Rucker",
  "Rush",
  "Russell",
  "Russell",
  "Saint Marys",
  "Sandy",
  "Sandy",
  "Sappony",
  "Seneca",
  "Severn",
  "Shenandoah",
  "Shoemaker",
  "Sinking",
  "Skiffes",
  "Slate",
  "Slate",
  "Sleepy",
  "Smith",
  "Smith",
  "Snake",
  "Snow",
  "Somerton",
  "South Anna",
  "Stave",
  "South Branch Potomac",
  "South Buffalo",
  "South Fork Catoctin",
  "South Fork Clinch",
  "South Fork Elizabeth",
  "South Fork Falling",
  "South Fork Holston",
  "South Fork Powell",
  "South Fork Rivanna",
  "South Fork Roanoke",
  "South Fork Shenandoah",
  "South Fork South Branch Potomac",
  "South Fork Tye",
  "South Mayo",
  "South Meherrin",
  "South",
  "South Yeocomico",
  "Southern Branch Elizabeth",
  "Staunton",
  "Stewarts",
  "Stinking",
  "Stock",
  "Stony",
  "Straightstone",
  "Stuart",
  "Sugarland",
  "Swift",
  "Ta",
  "Taylors",
  "Tear Wallet",
  "Thornton",
  "Three",
  "Tinker",
  "Totuskey",
  "Tug",
  "Tye",
  "Upper Chippokes",
  "Upper Machodoc",
  "Walker",
  "Wallen",
  "Wards",
  "Ware",
  "Warwick",
  "West Fork Little",
  "West Little Seneca",
  "West Yeocomico",
  "Western Branch Elizabeth",
  "Whistle",
  "Whitetop Laurel",
  "Willis",
  "Wilson",
  "Wolf",
  "Yeocomico",
  "York",
  "Alloway",
  "Anacostia",
  "Antietam",
  "Back",
  "Ballenger",
  "Bear",
  "Bennett",
  "Big Annemessex",
  "Big Hunting",
  "Big Pipe",
  "Bird",
  "Blackwater",
  "Bodkin",
  "Bread and Cheese",
  "Broad",
  "Broad",
  "Budds",
  "Bush",
  "Bush",
  "Casselman",
  "Cabin John",
  "Carroll",
  "Catoctin",
  "Chester",
  "Chicamuxen",
  "Choptank",
  "Christina",
  "Conococheague",
  "Cuckold",
  "Curtis",
  "Deer",
  "Deep",
  "Difficult",
  "Dividing",
  "Double Pipe",
  "Dry Seneca",
  "Dueling",
  "Dundee",
  "Elk",
  "Evitts",
  "Fifteenmile",
  "Fishing",
  "Flintstone",
  "Frog Mortar",
  "Furnace",
  "Georges",
  "Great Seneca",
  "Gunpowder",
  "Gunpowder",
  "Gwynns",
  "Hawlings",
  "Harris",
  "Henson",
  "Herring",
  "Horsepen",
  "Indian",
  "Israel",
  "Jones",
  "Laurel",
  "Licking",
  "Limekiln",
  "Linganore",
  "Little Catoctin",
  "Little Choptank",
  "Little Conococheague",
  "Little Falls",
  "Little Gunpowder",
  "Little Hunting",
  "Little Monocacy",
  "Little Paint",
  "Little Patuxent",
  "Little Pipe",
  "Little Seneca",
  "Little Tuscarora",
  "Little Youghiogheny",
  "Lyons",
  "Magothy",
  "Marley",
  "Marsh",
  "Marshyhope",
  "Mattawoman",
  "Middle",
  "Middle Patuxent",
  "Middle",
  "Minnehaha",
  "Monocacy",
  "Moores",
  "Muddy",
  "Nanjemoy",
  "Nanticoke",
  "North Branch Patapsco",
  "North Branch Potomac",
  "North East",
  "Northeast Branch Anacostia",
  "Northwest Branch Anacostia",
  "Northwest Branch Patapsco",
  "Octoraro",
  "Oxon",
  "Owens",
  "Paint",
  "Patapsco",
  "Patuxent",
  "Piscataway",
  "Pocomoke",
  "Pomonkey",
  "Popes",
  "Port Tobacco",
  "Potomac",
  "Principio",
  "Rhode",
  "Rock",
  "Rock",
  "St. Marys",
  "Saltpeter",
  "Sams",
  "Sassafras",
  "Savage",
  "Seneca",
  "Severn",
  "Sideling Hill",
  "Sligo",
  "South Branch Patapsco",
  "South",
  "Stony",
  "Susquehanna",
  "Swanson",
  "Tenmile",
  "Toms",
  "Tonoloway",
  "Town",
  "Tuckahoe",
  "Tuscarora",
  "Watts",
  "West",
  "Western",
  "Western Branch Patuxent",
  "Wicomico",
  "Wills",
  "Winters",
  "Wye",
  "Youghiogheny",
]

export const riverTitles = [
  "River",
  "Canal",
  "Creek",
  "Channel",
  "Tributary",
  "Waterway",
  "Branch",
  "",
  "Watercourse",
  "Run",
  "Stream",
  "Branch",
  "Brook",
  "Fork"
]
